---
- name: "Piwik playbook"
  hosts: piwik
  user: $user
  sudo: yes
  sudo_user: root

  vars_files:
    - [ "vars/custom.yml", "vars/defaults.yml" ] # Load custom vars if present, otherwise use default Piwik settings
    - [ "vars/{{ ansible_os_family }}_dependencies.yml", "vars/os_defaults_dependencies.yml" ] # Dependencies based on OS
    - [ "vars/{{ ansible_os_family }}_apache.yml", "vars/os_defaults_apache.yml"] # Apache configuration
  tasks:
    - include: tasks/setup.yml

  handlers:
    - include: handlers/apache.yml
