---
- name: "Fail if no MySQL configuration"
  fail: msg="MySQL settings not defined"
  when_unset: ${mysql}
  tags:
    - piwik
    - checks

- name: "Fail if no sites defined"
  fail: msg="Define at least 1 site"
  when_unset: ${piwik.sites}
  tags:
    - piwik
    - checks