---
# Install MySQL dependencies
- name: "Install MySQL dependencies"
  action: ${ansible_pkg_mgr} pkg={{ item }} state=installed update-cache=yes
  with_items: dependencies.mysql
  register: mysql_packages
  tags:
    - piwik
    - database

- name: "Check if empty MySQL admin password"
  action: shell mysql -h {{ piwik.mysql.host }} -u {{ piwik.mysql.admin_user }} -e quit
  ignore_errors: True
  register: mysql_emptypass
  tags:
    - piwik
    - database

- name: "Change MySQL root password"
  action: shell mysqladmin -h {{ piwik.mysql.host }} -u {{ piwik.mysql.admin_user }} password {{ piwik.mysql.admin_pass }}
  when: mysql_emptypass|success
  tags:
    - piwik
    - database

# Manage Piwik database
- name: "Manage Piwik db"
  action: mysql_db encoding=utf8 name={{ piwik.mysql.piwik_db }} state=present login_user={{ piwik.mysql.admin_user }} login_password={{ piwik.mysql.admin_pass }} login_host={{ piwik.mysql.host }}
  register: mysql_dbcreated
  tags:
    - piwik
    - database

# Manage Piwik database user
- name: "Manage Piwik db-user"
  action: mysql_user name={{ piwik.mysql.piwik_user}} password={{ piwik.mysql.piwik_pass}} priv={{ piwik.mysql.piwik_db}}.*:ALL state=present login_user={{ piwik.mysql.admin_user }} login_password={{ piwik.mysql.admin_pass }} login_host={{ piwik.mysql.host }}
  tags:
    - piwik
    - database