---
# Fetch latest release GeoIP database
- name: "Fetch latest GeoIP database"
  action: get_url url={{ geoip.url }}/{{ geoip.file }} dest={{ piwik.locations.dest }}/misc/ mode=0660 owner={{ apache.user }} group={{ apache.group }}
  register: geoip_db
  tags:
    - piwik
    - geoip

# Extract GeoIP database
- name: "Extract GeoIP database"
  action: shell gunzip -c {{ piwik.locations.dest }}/misc/{{ geoip.file }} > {{ piwik.locations.dest }}/misc/{{ geoip.dest }}
  when: geoip_db.changed
  tags:
    - piwik
    - geoip