---
# Fetch the ldap plugin
- name: "Fetch LDAP plugin"
  action: get_url url=${ldap.url} dest=${piwik.plugin_dir}/${ldap.dest_file} owner=${piwik.www_user} group=${piwik.www_group} mode=0660
  register: ldap_plugin
  tags:
    - piwik

# Extract LDAP plugin
- name: "Extract LDAP plugin"
  action: shell unzip -o ${piwik.plugin_dir}/${ldap.dest_file} chdir="${piwik.plugin_dir}"
  when_changed: ${ldap_plugin}
  tags:
    - piwik

# Fix plugin dir permissions
- name: "Fix LDAP plugin dir permissions"
  file: path=${piwik.plugin_dir}/LoginLdap owner=${piwik.www_user} group=${piwik.www_group} state=directory recurse=yes
  tags:
    - piwik

# Enable LDAP plugin
- name: "Enable LDAP plugin"
  action: lineinfile dest=${piwik.dest_dir}/config/fragments/base_config.ini.php regexp="^PluginsInstalled" insertafter="^PluginsInstalled*Overlay" line="PluginsInstalled[] = \"LoginLdap\""
  tags:
    - piwik

# Activate LDAP plugin
- name: "Activate LDAP plugin"
  action: lineinfile dest=${piwik.dest_dir}/config/fragments/base_config.ini.php regexp="Plugins\[\] = \"Login*\"" line="Plugins[] = \"LoginLdap\""
  tags:
    - piwik

# Add Piwik ldap config
- name: "Add Piwik ldap config"
  action: template src=templates/ldap_config.ini.php.j2 dest=${piwik.dest_dir}/config/fragments/ldap_config.ini.php owner=${piwik.www_user} group=${piwik.www_group} mode=0640
  tags:
    - piwik