---
# Execute some tests first
- include: tasks/checks.yml

# Manage Piwik MySQL db
- include: tasks/db.yml

# Install Piwik
- include: tasks/piwik.yml

# Install GeoIP database file
- include: tasks/geoip.yml

# Install LDAP plugin
- include: tasks/ldap.yml